AWSTemplateFormatVersion: '2010-09-09'
Description: CloudAuditor - Cross-Account Execution Role and Resource Explorer for Member Accounts

Parameters:
  HubAccountId:
    Type: String
    Description: The AWS Account ID where CloudAuditor Lambdas are deployed.
    AllowedPattern: '^\d{12}$'
    ConstraintDescription: Must be a 12-digit AWS Account ID.

Resources:
  # Resource Explorer LOCAL index for this account
  # Enables CloudAuditor discovery engine to inventory resources via the Search API
  ResourceExplorerIndex:
    Type: AWS::ResourceExplorer2::Index
    Properties:
      Type: LOCAL

  CloudAuditorExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CloudAuditorExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${HubAccountId}:role/cloudauditor-lambda-role-dev'
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CloudAuditorReadOnlyAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - iam:Get*
                  - iam:List*
                  - ec2:Describe*
                  - rds:Describe*
                  - s3:GetBucket*
                  - s3:List*
                  - resource-explorer-2:Search
                  - resource-explorer-2:ListIndexes
                  - resource-explorer-2:GetIndex
                  - resource-explorer-2:ListSupportedResourceTypes
                  - config:ListDiscoveredResources
                  - cloudcontrol:ListResources
                Resource: '*'

Outputs:
  RoleArn:
    Description: The ARN of the CloudAuditor Execution Role
    Value: !GetAtt CloudAuditorExecutionRole.Arn

  ResourceExplorerIndexArn:
    Description: The ARN of the Resource Explorer index
    Value: !GetAtt ResourceExplorerIndex.Arn
